---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: ks-tenant-dev
spec:
  interval: 5m0s
  path: ./tenants/kla/dev
  prune: true
  serviceAccountName: flux-reconciler
  sourceRef:
    kind: GitRepository
    name: tenant-git-repository
  validation: client
  targetNamespace: dev
  dependsOn:
    - name: tenant-commons-dev