---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: fleet-tenant-app-sync
spec:
  interval: 5m0s
  path: <change-it-with-patch>
  prune: true
  serviceAccountName: flux-reconciler
  sourceRef:
    kind: GitRepository
    name: <change-it-with-patch>
  validation: client