---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: platform-repo
  namespace: flux-system
spec:
  interval: 1m0s
  ref:
    branch: main
  secretRef:
    name: platform-repo-auth
  url: ssh://git@github.com/rkdutta/platform-repo

# ---  
# apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
# kind: Kustomization
# metadata:
#   name: fleet-platform-sync
#   namespace: flux-system
# spec:
#   interval: 5m0s
#   path: ./repository
#   prune: true
#   sourceRef:
#     kind: GitRepository
#     name: platform-repo
#   validation: client
#   targetNamespace: platform