---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: fleet-tenant-app-sync
spec:
  path: ./deploy/tenants/dev
  sourceRef:
    kind: GitRepository
    name: tenant-git-repository