---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: fleet-tenant-sync
spec:
  interval: 5m0s
  path: ./deploy/configs/tenants/kla/dev/
  prune: true
  serviceAccountName: flux-reconciler
  sourceRef:
    kind: GitRepository
    name: app-git-repository
  validation: client