apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: tenant-kla-commons-dev
#  namespace: dev
spec:
  interval: 5m0s
  path: ./commons/
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system 
    namespace: flux-system
  validation: client
  targetNamespace: dev