---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: flux-reconciler
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: admin
subjects:
  - kind: ServiceAccount
    name: flux-reconciler
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: patch-permission
  namespace: ccs-vp-dev-kla
rules:
- apiGroups:
  - kustomize.toolkit.fluxcd.io
  resources:
  - kustomizations
  verbs:
  - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: patch-permission
  namespace: ccs-vp-dev-kla
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: patch-permission
subjects:
- kind: ServiceAccount
  name: flux-reconciler
  namespace: ccs-vp-dev-kla